### PR TITLE
Update moni-deployment.yaml

### PR DESCRIPTION
**Pull request by hamidoke**
## Description
Updating CI/CD deployment to remove auto push

## Related issues and discussion
#{Issue Number}

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Validate the JS and HTML files with `grunt validate` to detect errors and potential problems in JavaScript code.

- [x] Run the tests by opening `test/SpecRunner.html` in the browser to make sure you didn't break anything.

- [x] If you have multiple commits please combine them into one commit by squashing them.

- [x] Read and understood the contribution guidelines at `community-app/Contributing.md`.

### CODE REVIEW

**Comment by Napho** [comment]
@hamidoke  does this mean that any push to this branch will go to production or is there trigger to get it to production?

**Comment by hamidoke** [comment]
It means we would have to trigger it to push to prod, but I will add auto push for dev

**Comment by hamidoke** [comment]
until we figure it out prod

**Review by Napho — APPROVED** [review]
LGTM

**Review by hero78 — APPROVED** [review]
Looks ok

**Pull request merged**
